#index:
#    path: /
#    controller: App\Controller\DefaultController::index

customer_list:
  path: /api/v1/customers
  controller: App\Controller\CustomerController:indexAction
  methods: [GET]
  

customer_create:
  path: /api/v1/customers
  controller: App\Controller\CustomerController:createAction
  methods: [POST]

customer_update:
  path: /api/v1/customers/{customerId}
  controller: App\Controller\CustomerController:updateAction
  methods: [PUT]
  requirements:
    customerId: '\d+'

customer_delete:
  path: /api/v1/customers/{customerId}
  controller: App\Controller\CustomerController:deleteAction
  methods: [DELETE]
  requirements:
    customerId: '\d+'